config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :notes
  resources :pet_vaccines
  resources :pets
  resources :vaccines
  resources :users

  root to: 'pets#index'

  namespace :admin do
    root to: 'dashboard#index'
  end

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  # Tiene muchas notes
  # pero se obtienen de buscar los atributos
  # notable_type = Pet, notable_id = id
  has_many :notes, as: :notable
  belongs_to :user
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  expose(:pets)
  expose(:pet, attributes: :pet_params)

  # POST /pets
  # POST /pets.json
  def create
    respond_to do |format|
      if pet.save
        format.html { redirect_to pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: pet }
      else
        format.html { render :new }
        format.json { render json: pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if pet.update(pet_params)
        format.html { redirect_to pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: pet }
      else
        format.html { render :edit }
        format.json { render json: pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).permit(:name, :owner_id, :birthday)
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.slim
= form_for pet do |f|
  - if pet.errors.any?
    #error_explanation
      h2 = "#{pluralize(pet.errors.count, "error")} prohibited this pet from being saved:"
      ul
        - pet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owner_id
    = f.number_field :owner_id
  .field
    = f.label :birthday
    = f.datetime_select :birthday
  .actions = f.submit 'Enviar'

app/views/pets/edit.html.slim
h1 Editar mascota

== render 'form'

= link_to 'Mostrar', pet
'|
= link_to 'Ir al listado', pets_path

app/views/pets/index.html.slim
h1 Mascotas

table
  thead
    tr
      th Nombre
      th Propietario
      th Fecha de Nacimiento
      th
      th
      th

  tbody
    - pets.each do |pet|
      tr
        td = pet.name
        td = pet.owner_id
        td = pet.birthday
        td = link_to 'Mostrar', pet
        td = link_to 'Editar', edit_pet_path(pet)
        td = link_to 'Eliminar', pet, data: {:confirm => 'Está usted seguro?'}, :method => :delete

br

= link_to 'Agregar mascota', new_pet_path

app/views/pets/new.html.slim
h1 Nueva mascota

== render 'form'

= link_to 'Ir al listado', pets_path

app/views/pets/show.html.slim
p#notice = notice

p
  strong Name:
  = pet.name
p
  strong Owner:
  = pet.owner_id
p
  strong Birthday:
  = pet.birthday

= link_to 'Edit', edit_pet_path(pet)
'|
= link_to 'Back', pets_path