config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :notes
  resources :pet_vaccines
  resources :pets
  resources :vaccines
  resources :users

  root to: 'pets#index'

  namespace :admin do
    root to: 'dashboard#index'
  end

end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  expose(:vaccines)
  expose(:vaccine, attributes: :vaccine_params)

  # POST /vaccines
  # POST /vaccines.json
  def create
    respond_to do |format|
      if vaccine.save
        format.html { redirect_to vaccine, notice: 'Vaccine was successfully created.' }
        format.json { render :show, status: :created, location: vaccine }
      else
        format.html { render :new }
        format.json { render json: vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccines/1
  # PATCH/PUT /vaccines/1.json
  def update
    respond_to do |format|
      if vaccine.update(vaccine_params)
        format.html { redirect_to vaccine, notice: 'Vaccine was successfully updated.' }
        format.json { render :show, status: :ok, location: vaccine }
      else
        format.html { render :edit }
        format.json { render json: vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.json
  def destroy
    vaccine.destroy
    respond_to do |format|
      format.html { redirect_to vaccines_url, notice: 'Vaccine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def vaccine_params
    params.require(:vaccine).permit(:name, :periodicity)
  end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/vaccines/_form.html.slim
= form_for vaccine do |f|
  - if vaccine.errors.any?
    #error_explanation
      h2 = "#{pluralize(vaccine.errors.count, "error")} prohibited this vaccine from being saved:"
      ul
        - vaccine.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :periodicity
    = f.number_field :periodicity
  .actions = f.submit 'Enviar'

app/views/vaccines/edit.html.slim
h1 Editar vacuna

== render 'form'

= link_to 'Mostrar', vaccine
'|
= link_to 'Ir al listado', vaccines_path

app/views/vaccines/index.html.slim
h1 Vacunas

table
  thead
    tr
      th Nombre
      th Aplicación (semanas)
      th
      th
      th

  tbody
    - vaccines.each do |vaccine|
      tr
        td = vaccine.name
        td = vaccine.periodicity
        td = link_to 'Mostrar', vaccine
        td = link_to 'Editar', edit_vaccine_path(vaccine)
        td = link_to 'Eliminar', vaccine, data: {:confirm => 'Está usted seguro?'}, :method => :delete

br

= link_to 'Nueva Vacuna', new_vaccine_path

app/views/vaccines/new.html.slim
h1 Nueva vacuna

== render 'form'

= link_to 'Ir al listado', vaccines_path

app/views/vaccines/show.html.slim
p#notice = notice

p
  strong Name:
  = vaccine.name
p
  strong Periodicity:
  = vaccine.periodicity

= link_to 'Edit', edit_vaccine_path(vaccine)
'|
= link_to 'Back', vaccines_path